### ISSUE TITLE
Problem with plugin 79 "Find VMs in Uncontrolled Snapshot Mode"

### ISSUE THREAD

**Issue by jcmachadouga** [alanrenouf/vCheck-vSphere#381] opened 2015-04-30 20:44 UTC
vCheck allways hungs on plugin 79.... Stays in there for couple of hours.

**Comment by vScripter** [comment] 2015-04-30 21:28
Can you provide some information on your environment:
* PowerCLI Version
* PowerShell Version
* vSphere Version
* vCheck Version

Does is just hang indefinitely and you have to force-quit or are you getting an error?

Has it worked in the past for you, at all?

**Comment by jcmachadouga** [comment] 2015-05-04 18:43
It worked before, but not with the new version after I upgrade vcheck and the plugins. It looks like is taking too long and the connection gets closed... 

PS: 

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

PowerCli:

PowerCLI Version
----------------
   VMware vSphere PowerCLI 5.5 Release 1 build 1295336
---------------
Snapin Versions
---------------
   VMWare AutoDeploy PowerCLI Component 5.5 build 1262826
   VMWare ImageBuilder PowerCLI Component 5.5 build 1262826
   VMware vCloud Director PowerCLI Component 5.5 build 1295337
   VMware License PowerCLI Component 5.5 build 1265954
   VMware VDS PowerCLI Component 5.5 build 1295334
   VMware vSphere PowerCLI Component 5.5 build 1295334

Vsphere:
5.5.0 build 1891313

Vcheck:
6.23-alpha-3



[13:24:58] ..start calculating VMs in uncontrolled snapshot mode by Rick Glover, Matthias Koehler v1.3 [94 of 108]
Get-Datacenter : 5/4/2015 2:04:13 PM    Get-Datacenter        The underlying connection was closed: Could not
establish trust relationship for the SSL/TLS secure channel.
At C:\scripts\vCheck\Plugins\60 VM\79 Find VMs in Uncontrolled Snapshot Mode.ps1:10 char:11
+     $DC = Get-Datacenter -VM $eachVM.Name
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Datacenter], ViError
    + FullyQualifiedErrorId : Client20_QueryServiceImpl_RetrievePropertiesEx_ViError,VMware.VimAutomation.ViCore.Cmdle
   ts.Commands.GetDatacenter

**Comment by Sneddo** [comment] 2015-05-05 03:16
Ah, it's the problem discussed in Issue #217...

**Comment by Bendy22** [comment] 2015-06-15 12:31
I am new to vCheck and I was getting stuck on plugin 79 as well. It doesn't look like it's resolved yet, so I moved that plugin outside the vCheck folder structure so it would be skipped. That works around the issue for me. It takes just a few minutes to run this way - very acceptable performance for a once a day script.

**Comment by Sneddo** [comment] 2016-03-03 21:47
Duplicate of #217

**Closed by Sneddo** 2016-03-03 21:47 UTC
Labels: error, ready
