### ISSUE TITLE
Report is emailed even though it is blank

### ISSUE THREAD

**Issue by cwiley2566** [alanrenouf/vCheck-vSphere#512] opened 2016-11-28 19:56 UTC
I set email report even if its blank to false but I still get an email? Am I missing something?
# Send the report by e-mail even if it is empty?
$EmailReportEvenIfEmpty = $false

**Comment by Sneddo** [comment] 2016-11-28 21:32
hmmmm can you attach a copy of the report?

What do you have $TimeToRun and $reportOnPlugins set to? If they are $true, this is probably the cause. Might need to exclude these from counting towards an empty report...

**Comment by cwiley2566** [comment] 2016-11-29 12:50
I thought that too but I set them to false:
# Do you want to include plugin details in the report?
$reportOnPlugins = $false
# List Enabled plugins first in Plugin Report?
$ListEnabledPluginsFirst = $false
# Set the following setting to $true to see how long each Plugin takes to run as part of the report
$TimeToRun = $false
# Report on plugins that take longer than the following amount of seconds
$PluginSeconds = 30
# End of Settings

**Comment by cwiley2566** [comment] 2016-11-29 12:52
![capture](https://cloud.githubusercontent.com/assets/22579161/20710495/b109ce8e-b608-11e6-9671-ad6455226038.JPG)
A screen shot of the report is attached.

**Comment by Sneddo** [comment] 2016-11-29 20:40
hmmm interesting!

Maybe try exporting the $PluginResult variable so we can see why it is setting $emptyReport to $false (which should only happen if there is at least one result in $PluginResult that has some output from a plugin). Add `$pluginReport | Export-Clixml ./PluginResult.xml` to the start of the output section around line 820.

Then we can `Import-Clixml .\PluginResult.xml` and see what is in the variable...

Out of interest, what version of Powershell are you running? From memory PS2.0 and lower had some quirky behavior with foreach loops, which would always iterate once even on an empty variable...though $Plugin.Details _should_ still be false...

**Comment by cwiley2566** [comment] 2016-11-30 13:20
I am not sure what you are looking for but this is the contents of pluginresults.xml
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Nil />
</Objs>

**Comment by cwiley2566** [comment] 2016-11-30 13:36
![capture](https://cloud.githubusercontent.com/assets/22579161/20754261/1da22d46-b6d8-11e6-80ba-5790e3c7d0da.JPG)

**Comment by Sneddo** [comment] 2016-11-30 21:30
Yeah interesting, the result is null...maybe we can try an additional check.

What version of Powershell are you using?

**Comment by cwiley2566** [comment] 2016-12-05 13:46
Powershell = 4.0
 VMware vSphere PowerCLI 6.3 Release 1 build 3737840
 vCheck = 6.23

**Comment by Sneddo** [comment] 2016-12-09 00:46
OK, I worked out what is causing this.

The connection plugin is returning the status messages as content, so technically the plugin has content even if it isn't displayed.

I've pushed a fix to the dev branch

**Comment by cwiley2566** [comment] 2016-12-09 12:51
Ok thanks very much!!

**Closed** 2016-12-12 03:40 UTC

**Comment by bossnass** [comment] 2018-03-09 12:11
Hello,

What was the actual fix for the issue, because I am still encountering it, despite using vCheck v6.25?
Also:
PowerShell = 5.1.15063.786
PowerCLI = 6.5.3 build 6826660

As a workaround I have commented out all Write-CustomOut lines, which ceased the unnecessary output in that plugin.
