### ISSUE TITLE
Logging suggestion 

### ISSUE THREAD

**Issue by samuk912** [alanrenouf/vCheck-vSphere#487] opened 2016-09-07 09:23 UTC
[https://github.com/samuk912/Powershell](url)

Hi
I would like to suggest having the vChecker script make a log so when it runs as a scheduled task you can go back and find out if there was any issues.  I have uploaded the WriteLog.ps1 as an example that I've used on some of my scripts.
regards
Sam

**Comment by PaulWalkerUK** [comment] 2016-09-07 22:10
That link gives me a 404 unfortunately.

Another option might be [log4net](https://logging.apache.org/log4net/). I successfully used it with PowerShell a few years ago. I'm not going to claim any expertise or that I did it the _right_ way or the _best_ way, but I could go take another look at what I did and put up a few notes if anyone would be interested. I liked it because it's pretty flexible and configurable through a config file - you just put loads of log messages in the code at different log levels, then users can just tweak the config file to control what actually gets output, as well as the format, etc. It was pretty nice once I got it working!

**Comment by samuk912** [comment] 2016-09-08 07:33
Hi
sorry about the link below the link should be fixed 
[My Repo](https://github.com/samuk912/Powershell)

**Comment by Sneddo** [comment] 2016-09-11 22:51
This should be easy enough to implement, we have the Write-CustomOut function that most output should use, should be easy enough to log this output to a file as well. 

We would probably need to expand on this a bit to capture errors, but wrapping the plugin execution in a try/catch block should mostly capture this...

**Comment by Sneddo** [comment] 2016-10-12 03:57
Closing this issue, effectively a duplicate of #414

**Closed by Sneddo** 2016-10-12 03:57 UTC
