### ISSUE TITLE
Connection Settings Plugin HTML Output

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#389] opened 2015-05-22 13:57 UTC
I recently had to re-image my vCheck machine, and after re-installing everything I am seeing an output in the HTML report for the Connection Settings plugin that I have never seen before.
![vcheck_connection_settings](https://cloud.githubusercontent.com/assets/8209710/7771863/5d9bbcc8-0068-11e5-9125-6754bba40ee5.PNG)

As you can see from the screen shot, the HTML report shows a list of numbers for this plugin and I don't understand what this is telling me or why the plugin is showing anything at all.

I'm running PowerShell v3.0, PowerCLI v5.5 Release 2 Patch 1, and the latest vCheck code from the dev branch.

**Comment by Sneddo** [comment] 2015-05-22 14:05
Yep, I found this earlier today as well. Removing Write-Host is the cause I believe, as the status messages get passed back to vCheck. We can get around this by setting display to none.

**Comment by MasterChiefJon** [comment] 2015-05-22 14:19
I tested it by setting:  $Display = "None"
and that changed the HTML output from what I was seeing before, to showing the results of the "Write-CustomOut" commands in the Connection Settings plugin (lines 114-134).

**Comment by Sneddo** [comment] 2015-05-24 22:46
hmmmmm we don't actually have a case for $display = "None" around line 808. If we set details to null there it should fix this up.

```"None" { $pr.Details = $null }```

The Style should then only do the replacement if $pr.Details is not null. I have a bit to get done today, so will try to get a fix for this committed if I get a chance.

**Comment by MasterChiefJon** [comment] 2015-05-27 12:16
I added that at line 809 (the first entry under the switch statement) and ran a test.  It worked.
So this change in vCheck.ps1 and the line $Display = "None" in the Connection Settings plugin fixed it.

**Comment by Sneddo** [comment] 2015-05-28 02:58
Yeah cool, will have to merge this change at some point...

**Closed** 2016-03-04 02:09 UTC
Labels: bug
